### ISSUE TITLE
Mozilla firefox broken JS

### ISSUE THREAD

**Issue by VitaliyBoyko** [wyomind/cronscheduler#16]
Hi guys!
Have an issue with Firefox and minified JS.
![2018-09-06_14-41-25](https://user-images.githubusercontent.com/20116393/46470562-bc902d80-c7df-11e8-908c-f772c9167032.png)
![859f2a4de4](https://user-images.githubusercontent.com/20116393/46470667-1abd1080-c7e0-11e8-98e1-2020eacca673.jpg)
Timeline page - when the user hovers cursor to the task on schedule - popup with information doesn`t appear. It comes along with errors in the console which you can see on the second screenshot.
It would be great to see any ideas how to fix it. Thanks!

**Comment by wyomind** [comment]
-- Please reply above this line --


            Hey Wyomind/cronscheduler,

Since we haven't heard from you on this issue in a while, we're
marking this ticket closed. 

Feel free to contact us at any time if you need. To do so simply log
into your Wyomind account and go to 'My account > My tickets' to
create a new one. 

Best Regards,
The Wyomind Team

**Comment by wyomind** [comment]
-- Please reply above this line --

Hey Wyomind/cronscheduler,

Thank you for your message.

 Your request has been correctly submitted.
     
 We’ll be getting back to you as soon as possible!

 Best Regards,
 The Wyomind Team
